### ISSUE TITLE
Installation details for linux based system

### ISSUE THREAD

**Issue by gowtham06** [airavata-courses/rip#16]
Its good that you have clearly mentioned the installation details in details. But can you please add the procedures for linux based systems as most of the production based servers are linux based.

**Comment by jitendraselvam** [comment]
I will fix that in the next iteration to add System OS checks and change the files accordingly. Thanks for the feedback.

**Comment by gowtham06** [comment]
Cool. Then am closing this issue as its part of your enhancement for the next iteration.
