### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by gowtham06** [airavata-courses/rip#17]
Am trying to do a maven build to set up the thrift server. But the maven build is failing due to **" EchoServiceHandlerTests.initializationError » Objenesis java.lang.reflect.Invo..."**.

Please find the screen shot of the issue here.
![screen shot 2018-09-25 at 10 04 58 am](https://user-images.githubusercontent.com/5094829/46019758-d5dffe00-c0aa-11e8-8dc4-0db57c658fc1.png)

**Comment by jitendraselvam** [comment]
I will have a look into the test cases.

**Comment by jitendraselvam** [comment]
could you run "mvn clean install -U" and try it once more ? If it still persists can you send me the post the snapshot of mvn "dependency::tree"

This seems to me like there is some dependency missing.

**Comment by gowtham06** [comment]
Hi , I tried with "mvn clean install -U". Still the build is not happening.
PFA the screenshot here.
![screen shot 2018-09-25 at 4 03 20 pm](https://user-images.githubusercontent.com/5094829/46039852-c1b4f480-c0dc-11e8-9f16-8dc40df60451.png)

**Comment by jitendraselvam** [comment]
Hi I tried to recreate this issue. I used Hulk system and imported a fresh code into a folder and ran mvn clean install -U 

![test](https://user-images.githubusercontent.com/13906298/46040180-98e12f00-c0dd-11e8-9735-2bd8a8170bf0.png)

It did build successfully and the test cases ran successfully. Maybe this might require some closer inspection.

**Comment by gowtham06** [comment]
Well , I tried on my Mac. Let me give it a try in hulk/burrows/silos.
But how can you configure kafka on IU systems. You need to get some credentials to do that I think.
(I assume you need Kafka and the zookeeper running to test the end-end functionality).

**Comment by jitendraselvam** [comment]
Could you try doing it on a local windows machine ? since the project operates based on window's directories. My team mate and I are working on making it work on linux and windows.

Sorry for the inconvenience caused.

**Comment by gowtham06** [comment]
@jitendraselvam  no problem. Will check it.

Thanks,
Gowtham

**Comment by gowtham06** [comment]
Closing the issue #17 as linux/unix compatibility is part of their next iteration.
