### ISSUE TITLE
Need documentation to run zookeeper and Kafka on unix/linux machines

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/rip#20]
Hello, 

Please add documentation to run the commands on unix/linux machines for zookeeper and Kafka.
Steps to install them and run them.

Thanks,
Nawaz

**Comment by jitendraselvam** [comment]
Thank you @nawazkh  I will refer this link to update the wiki.

**Comment by jitendraselvam** [comment]
Added the documentation. Closing issue #20 . Thank you for your feedback.
