### ISSUE TITLE
Peer review Summary

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/rip#21]
- Branches Thrift_Server, Kafka_Byte running properly. 
- Zookeeper, Kafka builds successfully.
- Checking branch Django_module

**Comment by nawazkh** [comment]
Please update the command to run Django_Module to be using python3.
- thrifty package needed to be installed prior starting the server.

**Comment by nawazkh** [comment]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/25679594/46056178-65be9000-c11d-11e8-92b2-7041b607e35f.png">

Error while executing manage.py runserver.
Shall I try running this command using pip2?

**Comment by jitendraselvam** [comment]
Hi @nawazkh. Sorry to hear that the Django_Module is not working. 

There is a secret client hidden in the ThriftServer module. 

You can still test our other two branches by running the "MightWorkClient.java" inside the ThriftServer module. (The client works, the name is deceiving sorry about that). 

The client allows you to upload, download and echo messages. Hope that helps :)
