### ISSUE TITLE
Maven build failure for Thrift

### ISSUE THREAD

**Issue by gowtham06** [airavata-courses/rip#38]
Errors in maven build for thrift server. Hereby I have attached the snapshot for the errors
![screen shot 2018-10-24 at 6 49 05 pm](https://user-images.githubusercontent.com/5094829/47466102-c1804580-d7bd-11e8-954c-ba3c5d9d387a.png)

Thrift build is supported for Mac/Linux systems right? I was getting a similar error for the assignment 1 also. Let me know.

**Comment by gowtham06** [comment]
Sorry for the troubles. Maven build was success full when I skipped the tests. However when am trying to start the application, am getting this error "Error starting Tomcat context". Below is the screen shot of the error
![screen shot 2018-10-24 at 7 26 45 pm](https://user-images.githubusercontent.com/5094829/47467190-05297e00-d7c3-11e8-9d25-2b573f565f85.png)

**Comment by gowtham06** [comment]
This might be the issue with the directory "sharedDirectory" . Will the application be dependent on file system (windows/linux). Please let me know regarding this.

**Comment by jitendraselvam** [comment]
> This might be the issue with the directory "sharedDirectory" . Will the application be dependent on file system (windows/linux). Please let me know regarding this.

We made the project independent of the operating system as per your request in the last peer review. It works on linux and windows file systems.

**Comment by jitendraselvam** [comment]
I tried after pulling a fresh code and tried it here are the [logs](http://s000.tinyupload.com/?file_id=06824983279610973049) I am not able to recreate it on my system nor my friend's system.
