### ISSUE TITLE
VueJs client

### ISSUE THREAD

**Issue by gowtham06** [airavata-courses/rip#39]
Out of curiosity, why is there a need for VueJS client. npm has a package for vuejs right for doing things like "vue create", "vue serve" etc.?

**Comment by soutri** [comment]
We are not using VueJs client .
Did you mean Vue-CLI ? 
Vue-CLI is just a command line interface  which we used for quickly scaffolding Single Page Applications.

**Comment by gowtham06** [comment]
Just like "express" in node js right? Cool. Thanks. Closing the issue
