### ISSUE TITLE
Peer Review assignment 4

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/rip#55]
Hello Team,

I am starting the peer review for assignment 4.

Thanks,
Nawaz

**Comment by jitendraselvam** [comment]
hey could you wait for a little longer till @Meghesh and @soutri finish their deployment ?

**Comment by nawazkh** [comment]
Hello Team,

The problem statement and proposed solutions are well documented. Specifications of the solution , such as storing data using NAS, is really good! 

Can you please provide me Jenkins user ID and password to check the build pipeline and link to check the application ?

Thanks,
Nawaz

**Comment by jitendraselvam** [comment]
Thanks navaz ! I've sent the details to you in chat.
